kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "db.pvc.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  {{- if typeIs "string" .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  accessModes:
    {{- .Values.pvc.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
