{{- if .Values.db.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name }}
type: Opaque
data:
  {{- range $key, $val := .Values.db.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
